[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E","F","I","W","C90"]
ignore = []
exclude = ["__pycache__", ".venv", "build", "dist"]
