name: Python Tests (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests (with coverage XML)
        run: |
          pytest -v --maxfail=2 --disable-warnings --cov=jarvis --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}   # Añádelo en Settings > Secrets > Actions
          files: coverage.xml
          flags: unittests
          verbose: true
