name: CI (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  ci:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black ruff

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (check)
        run: black --check .
